version: '3'
services:
  frontend:
    container_name: frontend
    image: nginx:1.17-alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/var/www/html/public
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - backend
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "9000:9000"
    env_file: backend/.env
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
      - redis
  worker:
    container_name: worker
    build: ./worker
    environment:
      - API_DOMAIN=frontend
      - REDIS_HOST=redis
    depends_on:
      - frontend
  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
    ports:
      - "8001:3306"
  redis:
    image: redis:4
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "8002:6379"
    volumes:
      - ./data/redis:/data
    restart: always
